### ISSUE TITLE
Formalize and Create Concept/POC for Operator-based Reconciliation in-cluster

### ISSUE THREAD

**Issue by jakobmoellersap** [kyma-incubator/reconciler#1018]
AC: 
- Finalize https://github.com/kyma-project/community/pull/654 
- Create POC Proposal to determine Value-Add of Operators used for Reconciliation 
- Create First Implementation Recommendations based on established Frameworks 
- Create Follow-Up Items and finalize Decision points from Concept 

- [x] [Setup of the Reconciler Operator Repository managing the Component Reconciliation inside SKR](https://github.com/kyma-incubator/reconciler/issues/1045) 
- [ ] [Watching and triggering actions for cluster resources](https://github.com/kyma-incubator/reconciler/issues/1046)
- [ ] [Configuration Management - User and central configuration](https://github.com/kyma-incubator/reconciler/issues/1048)

**Comment by jakobmoellersap** [comment]
closed in favor of https://github.com/kyma-project/kyma-operator/issues/8
