### ISSUE TITLE
Implement Provisioner Reconciler

### ISSUE THREAD

**Issue by akgalwas** [kyma-incubator/reconciler#320]
**Description**

Implement Kubernetes cluster provisioning functionality. 

**Acceptance criteria**

- [x] Define contract between Mothership and a new Reconciler responsible for Kubernetes cluster operations (documented)
  - What will be the payloads?
- [ ] Implement the new Reconciler that supports the following operations:
  - [ ] Cluster creation
  - [ ] Cluster removal
  - [ ] Cluster upgrade 
- [ ] Implement shoot reconciler with the following functionalities:
  - [ ] Configuring Gardener audit logs
  - [ ] Reacting on configuration changes performed by Gardener    
- [ ] Enhance Mothership API and data model
- [ ] Integrate Mothership with the new Reconciler
  - [ ] Implement scheduling and invoking cluster provisioning and upgrade operations
  - [ ] Implement logic for orchestrating Kubernetes cluster operations and Components Reconciler
- [ ] Provide developer documentation for the new component
    

**Reasons**

Reconciler is not able to provision Kubernetes cluster so the cluster needs to be created by an external system.

**Comment by janmedrek** [comment]
We need to consider adding additional options in comparison to the old API, for example, there were requests to provide a way of passing percentage string values for Gardener workers `maxSurge` and `maxUnavailable` fields.

**Comment by janmedrek** [comment]
Metrics for Provisioning/Deprovisioning should be exposed: https://github.tools.sap/kyma/backlog/issues/1036

**Comment by janmedrek** [comment]
We also need to include standard provisioning/deprovisioning metrics and expose them (TBD).

**Comment by janmedrek** [comment]
The reconciler should also take into account that some upgrades/changes may be performed on the Shoot CR - this can lead to desynchronization errors. Such cases should be handled.

**Comment by janmedrek** [comment]
Work-plan proposal:
- [ ] Discuss investigation results with the Reconciler team
  - Set up the contract between Mothership and Provisioner reconciler
- [ ] Prepare stub component/project for the defined API
  - Create Dockerfile
  - Create pipelines
- [ ] Implement the handlers / logic

**Comment by janmedrek** [comment]
We've aligned with the Reconciler team, the idea is to implement Provisioning Reconciler as one of the component reconcilers.

We would like to start with the MVP approach - implement only one functionality, for now, we will proceed with the rest later.
The best start would be to create a `provisioning` action. We can use some kind of callback URL until Mothership's API allows for kubeconfig upload.

**Comment by akgalwas** [comment]
There is the following plan for the MVP:
- [] Create a package for operating on Gardener shoots
- [] Agree interface with Mothership to be used to deliver kubeconfig
- [] Prepare a list of open questions for the next steps

**Comment by akgalwas** [comment]
For the MVP it was assumed that:
- Mothership API will be enhanced to allow providing Gardener cluster config. There will be a need to enhance Mothership to pass configuration to "Provisioning Reconciler" 
- "Provisioning Reconciler" will use Gardener kubeconfig mounted to the local filesystem. As a result "Provisioning Reconciler" must be deployed in a separate chart.

**Comment by akgalwas** [comment]
The current implementation in Provisioner adds shoot annotations to correlate shoot with a particular Runtime in Compass. There are the following annotations:
- `compass.provisioner.kyma-project.io/operation-id: {id}`
- `compass.provisioner.kyma-project.io/runtime-id: {id}`
- `kcp.provisioner.kyma-project.io/operation-id: {id}`
- `kcp.provisioner.kyma-project.io/runtime-id: {id}`

Operation ID is a Provisioner's operation ID so it will not be valid in the Reconciler context.   

There are the following questions to be answered:
- Is `CorrelationID` enough to match shoot with particular reconciler operation? Action metadata doesn't contain any other identifier that can be used to map Reconciler operation to shoot.
- How RuntimeID annotation will be added? Currently it contains Compass RuntimeID but

**Comment by akgalwas** [comment]
Provisioner have two responsibilities that are not directly connected to Provisioning but need to be implemented as a part of new "Provisioning Reconciler":
- Enabling audit logs on Gardener's shoot
- Updating cluster configuration in case of shoot modifications performed by the Gardener. Some cluster properties (such as Kubernetes version) may be automatically updated by Gardener. SRE experienced issues with upgrading Gardener clusters with Provisioner in case of modifications performed by Gardener. The issues root cause was the fact that Provisioner's database contained outdated values so that attempt to upgrade shoot failed (e.g. `kubernetesVersion` in Provisioner's database was older then the actual version installed in the cluster  )

**Comment by akgalwas** [comment]
In the current architecture, Hyperscaler Account Pool is implemented in Kyma Environment Broker. We need to consider at some point moving HAP to Provisioning Reconciler.

**Comment by janmedrek** [comment]
@akgalwas especially since we are considering introducing VNet-related logic, which, in my opinion, should not be coupled with the provisioning. That would make it 3 different components using Hyperscaler Account Pool logic, definitely material for a separate block.

**Comment by akgalwas** [comment]
It was decided that the Reconciler architecture will be modified to be more declarative. 
The main assumptions:
- Cluster Inventory is a single source of truth
- Sub reconcilers fetch data from Cluster Inventory and take actions

Details are covered in the following PR: https://github.com/kyma-project/community/pull/636/files
 
As a result we abandoned the concept of implementing "Provisioning Reconciler"

**Comment by janmedrek** [comment]
With the new approach described in https://github.com/kyma-project/kyma/issues/13759, we will be focusing on the declarative, CRD-based approach described here: https://github.com/kyma-incubator/reconciler/issues/1047.

There will be a follow-up ticket for the implementation.
