### ISSUE TITLE
Load and stress test for reconciler

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#329]
**Description**

The performance profile of the reconciler has to be analysed to identify performance bottlenecks and be aware about the thresholds / limits we should not exceeds.

AC:

* Implement a load test scenario for the reconciler (e.g. increase the number of parallel reconciliations until X reconciliations are running in parallel)
* measure the resource consumption of the mothership and component reconcilers and track these figures in a central dashboard
* visualise the recorded consumption data in the dashboard
* setup CI / CD pipeline for executing te load test

- [x] Setup a load test scenario
     - [x] Create a test script which creates X cluster entites the mothership
     - [x] implement a simple mock-component reconciler which is capable to retrieve requests from mothership and sends regularly heartbeat messages back
- [x] #774 
- [x] https://github.com/kyma-incubator/reconciler/issues/818

**Reasons**

Get awareness of the reconciler scalability, bottlenecks and performance thresholds / limits.

**Attachments**

**Comment by dariusztutaj** [comment]
https://github.tools.sap/kyma/security-scans/issues/11301

**Comment by adityabhatia** [comment]
Load and stress test focus moved to the kyma-operator at the moment

**Comment by janmedrek** [comment]
Functionalities of the Reconciler were migrated to the new architecture, this issue will not be worked on.
