### ISSUE TITLE
Move Compass Runtime Agent to the new Kyma modular architecture

### ISSUE THREAD

**Issue by janmedrek** [kyma-incubator/reconciler#419]
**Description**

According to this [concept](https://github.com/kyma-project/community/tree/main/concepts/modularization) concept we move towards modular architecture. Compass Runtime Agent will be an apart of Application Connector module. The architecture of the Kyma Control plane will be changed, and there will be a new component introduced called Compass Manager.

**Reasons**

Provisioner component that is responsible for registering Runtimes will be replaced by Provisioning Operator. The Provisioning Operator will no longer register Runtimes so that new component needs to be introduced.

**Acceptance Criteria**
- [ ] Compass Manager must register Runtimes in Compass Director
- [ ] Compass Manager must obtain One Time Token and create configuration secret for Compass Runtime Agent
- [ ] Compass Manager must detect that Application Connector module is installed in the Runtime
- [ ] Documentation prepared

**Comment by majakurcius** [comment]
Note to self: We should link the documentation issue here once we have it.

**Comment by janmedrek** [comment]
If the ClusterInventory does not have information about whether the cluster is already registered in Compass or not then it will always need to send the "all-existing-cluster-list" to the Compass Reconciler (which will later require comparison with Compass Reconciler database).

**Comment by akgalwas** [comment]
Steps.
1. Prepare POC for using [Runtime Watcher](https://github.com/kyma-project/runtime-watcher) for detecting Application Connector module. Scope:
   1. Prepare initial project structure with pipelines
   2. Define what resources should be observed (Kyma CRs?)
   3. Create operator with Kubebuilder
   4. Use Runtime watcher to get notifications from the Runtime watcher. Detect that module is installed adn print information to the log.
2. Productise the POC
   1. Implement registering Runtimes in Compass
   2. Implement getting One Time Token and pushing Compass Runtime Agent configuration to the Runtime
3. Prepare integration test

**Comment by Disper** [comment]
Duplicated by https://github.com/kyma-project/kyma/issues/16788 & https://github.tools.sap/kyma/backlog/issues/2183.

**Comment by Disper** [comment]
Duplicated by https://github.com/kyma-project/kyma/issues/16788.
