### ISSUE TITLE
Istio reconciler refactoring

### ISSUE THREAD

**Issue by strekm** [kyma-incubator/reconciler#543]
**Description**

**As-Is:**

Istio reconciler was first reconciler implemented, also not trivial one. At this time istio reconciler handles following responsibilities:  
 - installs / upgrades istio with istioctl
 - installs / upgrades istio related resources from the istio-configuration chart
 - synchronises sidecars after upgrade
 
**Refactoring Motivation:**

Istio reconciler should be reworked in a way that default istio reconciler **don't** manage istio resources from templates folder after istio was installed / upgraded via istioctl in reconcile action.  As this functionality is out of the box provided by the reconciler framework.
No longer managing (applying) those additional resources, like the grafana monitoring dahsboards, implys that all resources located in the component `istio-configuration`  will be automatically managed by the reconciler framework.
A first PoC on this brought the result that the istio-operator.yaml can not be simple applied by reconciler. Kyma uses the Istio Operator just as the configuration option and not using the Istio Operator Controller. Also it is necessary to have the possibility to overwrite values within the isio-operator.yaml what makes it not possible to simply move the file to a subfolder where helm would not consider it (Kyma 1 had this approach with the additional downside of having multiple istio-operator_xy.yaml files for each profile)

**Target Solution Design:**

Two components (istio + istio-resources) will be dealing with Istio.
First takes care of istio installation based on proper configuration within istio-operator.yaml, second (istio-resources) takes care of proper installation of istio related resources like grafana monitoring dashboards. 
Following task will be necessary to implement this design:

 
 AC: 
 
 - [x] [installation / upgrade of istio resources is handled by helm chart reconciler](https://github.com/kyma-project/kyma/issues/13113)
 - [x] [istio reconciler supports both components: istio & istio-configuration](https://github.com/kyma-incubator/reconciler/issues/698)
 - [x] [istio reconciler actions are well definied](https://github.com/kyma-incubator/reconciler/issues/705)
 - [x] installation / upgrade of istio via istioctl should be reconcile action
 - [x] proxy reset is implemented as post action
 - [x] istiooperator file is still part of templates
 - [x] uninstall of istio should be delete action
 - [x] istio resources from templates are no longer managed by istio reconciler
 - [x] [istio-configuration renamed to istio](https://github.com/kyma-project/kyma/issues/13114)
 - [x] [Documentation update for Istio refactoring](https://github.com/kyma-project/kyma/issues/13169)

 
**Reasons**

First step in getting rid of technical dept and preparing that istio reconciler don't takes care of deployment of additional resources

**Attachments**
