### ISSUE TITLE
Improve DB queries which take >10ms

### ISSUE THREAD

**Issue by tobiscr** [kyma-incubator/reconciler#733]
**Description**

The reconciler is still firing DB queries which have sometimes processing efforts far above 10ms.

These queries have to be investigated and optimised (e.g. by adding further indexes etc).

Please use [GCP DB insight](https://console.cloud.google.com/sql/instances/kyma-mps-stage-730c/insights;duration=PT1H;sort_by=TOTAL_EXEC_TIME?project=sap-ti-dx-kyma-mps-stage&ref=https:%2F%2Faccounts.google.com%2F&pli=1&rapt=AEjHL4NVNKfj7pzBRTsQ1T1AuWQNDNB-BXGd7SfU0Ab4b8Cmn82SDV7j9ukgGQ77YcA2_ieFUcXoYS1-L3UT1kPyy233ECozPw) for getting an overview of bad performing SQL statemets.

AC:
* GCP DB insights doesn't show any SQL queries fired by reconciler which are much higher than 10ms.

**Reasons**

Ensure DB is well performing even under high load.

**Tasks**

- [x] https://github.com/kyma-incubator/reconciler/pull/910
- [ ] https://github.com/kyma-incubator/reconciler/issues/851
- [x] https://github.com/kyma-incubator/reconciler/pull/905
- [x] https://github.com/kyma-incubator/reconciler/issues/920
- [x] https://github.com/kyma-incubator/reconciler/issues/921

**Attachments**

**Comment by veichtj** [comment]
I had a look at [GCP DB insight](https://console.cloud.google.com/sql/instances/kyma-mps-stage-730c/insights;duration=PT1H;sort_by=TOTAL_EXEC_TIME?project=sap-ti-dx-kyma-mps-stage&ref=https:%2F%2Faccounts.google.com%2F&pli=1&rapt=AEjHL4NVNKfj7pzBRTsQ1T1AuWQNDNB-BXGd7SfU0Ab4b8Cmn82SDV7j9ukgGQ77YcA2_ieFUcXoYS1-L3UT1kPyy233ECozPw) and analyzed the top four queries (in terms of generated load on the DB)
Overall I could not spot any low hanging fruit in terms of optimization, like one missing index or something similar. However there seem to be a bigger potential in restructuring the DB model from what it is build right now. At the moment there is no easy way like `select from x where cluster_id = y` to determine the current state (config and status etc) to a defined cluster, nor an easy way to determine all clusters in status xy, but both UseCases seem to be often used within the Code.
To determine this informations it looks like there are always three sequentiell, or even more, queries needed. Those seem to reflect in the top rated ones in GCP. 

Here are my findings, I focused on inventory* tables and on UseCase to find "clustersToReconcile" what seems to produce most of GCPInsight load.

- **inventory_clusters**: table has a combined primary key (runtime_id + version), version is a generated number out of a DB sequence, what ensures that it is always unique. Having a combined key in this format is not needed, either counting up a version (0,1,2..) + the runtime_id OR having a real ID generated from a DB sequence. Combining those two things makes it hard to determine current state, and is not needed.
Proposal: rename version to ID, remove runtime_id from PK, non-unique index for runtime_id

- **inventory_cluster_configs**: similar to inventory_clusters, table has a combined key out of "version", "runtime_id" and "cluster_version", but "version" is again from a DB sequence so it is always unique. That combination makes it difficult to determine the current configuration of a cluster.
Proposal: rename version to ID, rename cluster_version to cluster_id, change PK to only ID, create an indicator what marks one config version of a cluster as current, save the current status redundant, change FK like adjusted in inventory_clusters

- **inventory_cluster_config_statuses**:  the table is currently used for determining current status and current config_version and current cluster_version to a runtime_id all this needs to be done via using group clause and aggregate functions. This is quite expensive like we see in the GCP Insights, as this table is on the one hand persisting whole hierarchy of every cluster, also deleted clusters seem to be not deleted out of the inventory tables?
Proposal: rename columns accordingly to other two inventory tables, use this table only for writing history of reconcilations to have this traceable. After finishing a cluster reconcilation update additionally (redundant) the status of the cluster in inventory_cluster_config or in inventory_cluster, to avoid those heavy queries.

- **usage of `max(version)**:` Determining the latest version (config or cluster) with the aggregate function max can be dangerous, as the numbers are not incremented like a real version, instead it is created out of a DB sequence and there it is not ensured that the numbers are ascending, "just" unique. If first proposals are implemented this might be obsolete

- **for update**: Having reconciler run with postgres DB every query except one with aggregate or grouping do normal selects with "for update" what let the DB acquire a lock on those DB entries. This is very heavy and also the DB Insights shows there is a lot of "waiting for lock" time. Please verify if this is really needed, or if this could not be done in another way like optimistic locking.

- **UseCase specific DB views**: I have played a bit with the model and created an "overlay" model what reflects part of the above mentioned recommendations, please find attached the sql file with the DDL statements for the Views. The View v_cluster_inventory could be used to determine easily all cluster which need reconcilation with one query.

**Comment by veichtj** [comment]
[inventory-views.sql.txt](https://github.com/kyma-incubator/reconciler/files/8114916/inventory-views.sql.txt)

**Comment by jakobmoellersap** [comment]
Hey everyone, 
 think I figured out why we have such a high connection overhead, partly contributing to our load. I think we have bad behavior in 
`func (pcf *postgresConnectionFactory) NewConnection() (Connection, error)`
https://github.com/kyma-incubator/reconciler/blob/67d6459b9b280ec7895d254d5df3f5330c03bb5b/pkg/db/postgres.go#L168

Here's what happens when you request a new Connection to the DB:
https://github.com/kyma-incubator/reconciler/blob/67d6459b9b280ec7895d254d5df3f5330c03bb5b/pkg/db/postgres.go#L174-L177

However, this happens for **EVERY** call to NewConnection(). Now, the sql.Open(...) documentation says:

> Open can only validate its arguments without connecting to the database. To verify that the data source name is valid, invoke ping.
> The returned DB is safe for concurrent use by multiple goroutines and maintains its own pool of idle connections. Therefore, the Open function should only be called once. It is rarely necessary to close a DB.

This means effectively that this is not NewConnection() **but instead NewConnectionPool()**
This means that on each NewConnection() we create a new SQL pool. That means we have our perpetrator.

My suggestion for a fix would be to put a mutex-synced DB object behind the implementation and thus ensure that we can always have at most one pool active for every new call (or something similar that makes sure we do not open multiple times).

I implemented a sample (also with GORM ORM integration, which could be left out) in #897 for another task related to cleaning up our DB layer

**Comment by jakMoeller** [comment]
Hey everyone, here's the result of today's discussions and pair programming (thanks @jeremyharisch for the session and @tobiscr for the input on the process and analysis): #905 

important notes:
- We didn't join over the status table directly to not start the query plan on our largest table, which includes state changes on all reconciliations. This can be changed later in the view if we choose to transition from a unique table to a dedicated audit table for state change history
- We have two intermediate views to solve the "max" aggregations, one of them with a postgres specific distinct on (parsed the query plan there again and this looks like it does a normal max aggregate internally).
- There is also a details view so we can still read all the information from the state (but the query plan is also more complicated)

Here a few overviews on the Query Plans resulting from the Inventory views (right side shows cost percentile, we will see how it behaves in the staging environment).

Query Plan: only resolving the Latest Status
![image](https://user-images.githubusercontent.com/25387431/157080065-35c8db1c-6275-4066-9f36-49335534f790.png)

Query Plan: fetch all state related information (full resolve of the State object in the inventory as we have it now, we need to analyse what we need here)
![image](https://user-images.githubusercontent.com/25387431/157079935-75385c1a-4d59-468e-b917-9bdf64cbacfd.png)

@veichtj compared to your implementation we chose to not go for too many abstraction views but with subselects instead, if you think there are issues here, please let us know! Mid-Term we want to your approach to change the DB structure behind the views. We also renamed them a bit to make sure they fit into the inventory domain model.

**Comment by jakobmoellersap** [comment]
Connection Pooling is fixed in a small PR together with making sure we only instantiate one pool at any given time: #910

**Comment by jakobmoellersap** [comment]
Relevant DB Rework and SQL Injection Protection change: https://github.com/kyma-incubator/reconciler/issues/851

**Comment by jakobmoellersap** [comment]
After some further investigation and a hickup on the views after testing, I went in again and compared our current view with the execution plans of some modified statement: I went ahead and tried to combine the statement first to better analyze the query, starting with our original query plan:
![image](https://user-images.githubusercontent.com/64904610/158676559-53cd98b7-9292-4755-a626-a12c59ff4de5.png)

Note that on this query plan (taken from our first view approach) we are aggregating the **entire inventory_cluster_config_status as well as inventory_cluster_configs tables**. This leads to a huge load as we execute the max aggregation for calculating the latest status on the entire table set. This is caused by the fact that our views in postgres (even up to 14x) are materialized and the where condition limiting the config / runtime id is not propagated before the aggregation function.

When trying to implement a fix, I ended with a simplified (but huge) statement:

```sql
SELECT 
    ic.runtime_id,
    
    max(ic."version") AS cluster_id,
    
    max(icc."version") AS config_id, 
    
    max(iccs.id) AS status_id,
    
    ic.runtime,
    ic.metadata,
    ic.kubeconfig,
    ic.contract,
    
    icc.kyma_version,
    icc.kyma_profile,
    icc.components,
    icc.administrators,
    
    iccs.status,
    
    ic.created  as cluster_created_at,
    icc.created as config_created_at,
    iccs.created AS status_created_at
    
    FROM inventory_cluster_configs icc
        JOIN inventory_clusters ic 
        ON icc.cluster_version = ic."version"
        AND icc.runtime_id = ic.runtime_id
        
    JOIN inventory_cluster_config_statuses iccs 
        ON iccs.cluster_version = ic."version"
        AND icc.runtime_id = ic.runtime_id
        AND iccs.config_version = icc."version"
        
    WHERE 
        ic.deleted = FALSE 
        AND icc.deleted = FALSE 
        AND iccs.deleted = FALSE
        
        AND ic.runtime_id = '6' 
        AND icc."version"  = 6
        
GROUP BY 
ic.runtime_id,

ic.runtime,
ic.metadata,
ic.kubeconfig,
ic.contract,

icc.kyma_version,
icc.kyma_profile,
icc.components,
icc.administrators,

iccs.status,

ic.created,
icc.created,
iccs.created
```

Note how in this query I've also included a query filter based on the config and cluster_id which is our main query used in the inventory.

The result is a much simpler query plan:
![image](https://user-images.githubusercontent.com/64904610/158676417-f3f9a3bd-94dd-4eca-a384-2928b1526e77.png)

Note how in this case we are only using the explicit config version index on the status and have to purely iterate through the statuses based on the filter (in this case the Bitmap Heap Scan checks for config_version = 6 and the outer Index Scan on inventory_cluster_configs checks on the runtime_id, immediately discarding any value that does not fit the condition). The important part here is that the aggregate went to the very top of the query plan, making the max() calculations very cheap.

Now things get interesting when we try to encapsulate this in a view:
```sql
CREATE OR REPLACE VIEW test_status_details AS SELECT 
    ic.runtime_id,
    
    max(ic."version") AS cluster_id,
    
    max(icc."version") AS config_id, 
    
    max(iccs.id) AS status_id,
    
    ic.runtime,
    ic.metadata,
    ic.kubeconfig,
    ic.contract,
    
    icc.kyma_version,
    icc.kyma_profile,
    icc.components,
    icc.administrators,
    
    iccs.status,
    
    ic.created  as cluster_created_at,
    icc.created as config_created_at,
    iccs.created AS status_created_at
    
    FROM inventory_cluster_configs icc
        JOIN inventory_clusters ic 
        ON icc.cluster_version = ic."version"
        AND icc.runtime_id = ic.runtime_id
        
    JOIN inventory_cluster_config_statuses iccs 
        ON iccs.cluster_version = ic."version"
        AND icc.runtime_id = ic.runtime_id
        AND iccs.config_version = icc."version"
        
    WHERE 
        ic.deleted = FALSE 
        AND icc.deleted = FALSE 
        AND iccs.deleted = FALSE
        
GROUP BY 
ic.runtime_id,

ic.runtime,
ic.metadata,
ic.kubeconfig,
ic.contract,

icc.kyma_version,
icc.kyma_profile,
icc.components,
icc.administrators,

iccs.status,

ic.created,
icc.created,
iccs.created

SELECT * FROM test_status_details WHERE runtime_id = '6' OR config_id  = 6
```

Interestingly, when trying to bind this query into a view and externalizing the query, the query plan is again materialized, causing a much worse query execution:
![image](https://user-images.githubusercontent.com/64904610/158678322-367a054b-955f-49eb-a5a4-04d010a7d8bd.png)

Note here, that, compared to the pure SQL call, this view is not using the existing indices for a bitmap lookup and instead is doing an entire table lookup for both inventory_cluster_configs and inventory_cluster_config_statuses. The Where condition now sits in the Aggregation Step when calculating the max() values.

My conclusion is that the only way to correctly hint the database here that we want to first do a table lookup and then the max aggregation by using a direct SQL statement or Function call that does the same internally if we want to continue with the given max aggregation model.

Disclaimer: I tested this on Postgres 9 / 11 / 14 and the results did not change for me.
