### ISSUE TITLE
Testing Istio reconciler changes

### ISSUE THREAD

**Issue by strekm** [kyma-incubator/reconciler#785]
**Description**

Implement pipelines testing istio reconciler changes along with main reconciler changes. Pipeline should use reconciler built from sources, install istio along with other pre-req and trigger istio component tests. Pipeline should be mandatory and be triggered before merging PR to main as well as after merging. 

**AC**

- [x] [istio component test](https://github.com/kyma-incubator/reconciler/issues/798)
- [x] [pre main & post main mandatory pipeline testing Istio reconciler](https://github.com/kyma-project/test-infra/issues/4928)
- [x] [pre main & post main mandatory pipeline testing Istio reconciler](https://github.com/kyma-project/test-infra/issues/4930)

**Reasons**

It is possible to introduce bugs which are discovered either in KCP or in kyma cli.

**Attachments**

**Comment by mjakobczyk** [comment]
One remark: add dedicated VirtualService that exposes IngressGateway under `healthz.<domain>`. If it returns HTTP status 200 then OK, any other response is considered as failure.
For input please have a look at [VirtualService available in `Istio-resources` component](https://github.com/kyma-project/kyma/blob/main/resources/istio-resources/templates/virtualservice.yaml).
